#!bin/bash
IMAGE=$(pwd)/out/arch/arm64/boot/Image.gz-dtb
git clone -j32 https://github.com/najahiiii/aarch64-linux-gnu.git -b 4.9-mirror gcc

GCC="$(pwd)/gcc/bin/aarch64-linux-android-"
curl -s -X POST https://api.telegram.org/bot777070512:AAEJ7GaEJsZz0CFjkNdmBotsZJTndh_3MhE/sendMessage?chat_id=-1001187043208 -d "disable_web_page_preview=true" -d "parse_mode=html&text=<b>•• perf-gd2fdbf2a ••</b>%0ACompile Started"'!'"%0A<b>For device</b> <code>Rolex (Redmi 4A)</code>%0A<b>For Pie</b>%0A<b>Under Commit</b> <code>$(git log --pretty=format:'"%h : %s"' -1)</code>%0A<b>Compiler</b> <code>$(${GCC}gcc --version | head -n 1)</code>%0A<b>Compiler</b> <code>$(${GCCARM}gcc --version | head -n 1)</code>%0AStarted on <code>$(TZ=Asia/Jakarta date)</code>%0A<b>Build Status:</b> #untested"
tanggal=$(TZ=Asia/Jakarta date +'%H%M-%d%m%y')
START=$(date +"%s")
export ARCH=arm64
export KBUILD_BUILD_USER=builder
export KBUILD_BUILD_HOST=mi-server

# Sprunge
function sprunge() {
    cat build.log | curl -F 'sprunge=<-' http://sprunge.us > link
    HASIL="$(cat link)"
}

# Fin Error
function finerr() {
        sprunge
        curl -s -X POST https://api.telegram.org/bot777070512:AAEJ7GaEJsZz0CFjkNdmBotsZJTndh_3MhE/sendMessage?chat_id=-1001187043208 -d "disable_web_page_preview=true" -d "parse_mode=html&text=Build throw an error(s) | <b>Build logs</b> <a href='${HASIL}'>here</a>"
        exit 1
}
make -s -C $(pwd) O=out rolex_defconfig
make -s -C $(pwd) CROSS_COMPILE=${GCC} O=out -j32 -l32 2>&1| tee build.log
if ! [ -a $IMAGE ]; then
	finerr
	exit 1
fi
cp out/arch/arm64/boot/Image.gz-dtb AnyKernel/zImage
sprunge
cd AnyKernel
zip -r9 perf-gd2fdbf2a-pie-${tanggal}.zip *
END=$(date +"%s")
DIFF=$(($END - $START))
curl -F chat_id="-1001187043208" -F document=@"perf-gd2fdbf2a-pie-${tanggal}.zip" -F "disable_web_page_preview=true" -F "parse_mode=html" -F caption="Build took $(($DIFF / 60)) minute(s) and $(($DIFF % 60)) second(s). <b>Logs</b> <a href='${HASIL}'>here</a> | #sunny" https://api.telegram.org/bot777070512:AAEJ7GaEJsZz0CFjkNdmBotsZJTndh_3MhE/sendDocument
cd ..
rm -rf out
rm -rf AnyKernel/zImage
rm -rf AnyKernel/perf-gd2fdbf2a-pie*.zip
