#!bin/bash
IMAGE=$(pwd)/out/arch/arm64/boot/Image.gz-dtb
echo "Clone Toolchains and AnyKernel"
git clone -j32 https://github.com/fadlyas/zip.git AnyKernel
git clone -j32 https://github.com/najahiiii/aarch64-linux-gnu.git -b 49-mirror gcc
echo "Done"
GCC="$(pwd)/gcc/bin/aarch64-linux-android-"
tanggal=$(TZ=Asia/Jakarta date +'%H%M-%d%m%y')
START=$(date +"%s")
export ARCH=arm64
export KBUILD_BUILD_USER=Muhammadfadlyas
export KBUILD_BUILD_HOST=Semaphoreci
curl -s -F chat_id=-1001158707255 -F sticker="CAADBQADIwAD7bkQKyMZ6Vhta9h8Ag" https://api.telegram.org/bot804021619:AAGsNtz-PiDmnuyoIg_lpKVghK_8WmxSbIQ/sendSticker
}
# Send info channel
function sendinfo() {
        curl -s -X POST "https://api.telegram.org/bot804021619:AAGsNtz-PiDmnuyoIg_lpKVghK_8WmxSbIQ/sendMessage" \
                        -d chat_id=$-1001158707255 \
                        -d "disable_web_page_preview=true" \
                        -d "parse_mode=html" \
                        -d text="<b>SteelHeart♡ </b> new build is up%0AStarted on <code>SemaphoreCI</code>%0AFor device <b>ROLEX</b> (Redmi 4A)%0Abranch <code>$(git rev-parse --abbrev-ref HEAD)</code> (Android 9.0/Pie)%0AUnder commit <code>$(git log --pretty=format:'"%h : %s"' -1)</code>%0AUsing compiler: <code>$(${GCC}gcc --version | head -n 1)</code>%0AStarted on <code>$(TZ=Asia/Jakarta date)</code>%0A<b>SemaphoreCI Status</b> <a href='https://fadlyas.semaphoreci.com/workflows/${SEMAPHORE_WORKFLOW_ID}'>here</a>%0A<b>Build Status:</b> #untested"
}
# Send private info
function sendpriv() {
        curl -s -X POST "https://api.telegram.org/bot804021619:AAGsNtz-PiDmnuyoIg_lpKVghK_8WmxSbIQ/sendMessage" \
                        -d chat_id=$-1001158707255 \
                        -d "disable_web_page_preview=true" \
                        -d "parse_mode=html" \
                        -d text="SteelHeart♡ CI Started%0AJob Name: ${SEMAPHORE_JOB_NAME}%0ACommit point: <a href='https://github.com/fadlyas/android_kernel_xiaomi_8917/commits/${SEMAPHORE_GIT_SHA}'>$(git log --pretty=format:'"%h : %s"' -1)</a>%0A<b>Pipeline jobs</b> <a href='https://fadlyas.semaphoreci.com/jobs/${SEMAPHORE_JOB_ID}'>here</a>"
}
# Push kernel to channel
function push() {
        cd AnyKernel
	ZIP=$(echo SteelHeart*.zip)
	curl -F document=@$ZIP "https://api.telegram.org/bot804021619:AAGsNtz-PiDmnuyoIg_lpKVghK_8WmxSbIQ/sendDocument" \
			-F chat_id="$-1001158707255" \
			-F "disable_web_page_preview=true" \
			-F "parse_mode=html" \
			-F caption="Build took $(($DIFF / 60)) minute(s) and $(($DIFF % 60)) second(s). | <b>Build logs</b> <a href='${HASIL}'>here</a> | #Sunny <b>GCC 4.9.x </b>"
}
# Function upload logs to my own server paste
function paste() {
        cat build.log | curl -F 'steel=<-' http://104.248.229.33:8181 > link
        HASIL="$(cat link)"
}
# Fin Error
function finerr() {
        paste
        curl -s -X POST "https://api.telegram.org/bot804021619:AAGsNtz-PiDmnuyoIg_lpKVghK_8WmxSbIQ/sendMessage" \
			-d chat_id="$-1001158707255" \
			-d "disable_web_page_preview=true" \
			-d "parse_mode=markdown" \
			-d text="Job ${SEMAPHORE_JOB_NAME} throw an error(s) | **Build logs** [here](${HASIL})"
        exit 1
}
# Compile plox
function compile() {
        make -s -C $(pwd) O=out rolex_defconfig
        make -s -C $(pwd) CROSS_COMPILE=${GCC} O=out -j32 -l32 2>&1| tee build.log
            if ! [ -a $IMAGE ]; then
                finerr
                exit 1
            fi
        cp out/arch/arm64/boot/Image.gz-dtb AnyKernel/zImage
        paste
}
# Zipping
function zipping() {
        cd AnyKernel
        zip -r9 SteelHeart-${tanggal}.zip *
        cd ..
}
sendpriv
#sticker
sendinfo
compile
zipping
END=$(date +"%s")
DIFF=$(($END - $START))
push
